"""align schema with models: owner_id NOT NULL, experiment FKs

Revision ID: 8cb6e5b283ec
Revises: b7d2c94a1f30
Create Date: 2026-09-11 11:00:33.366857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import Connection


def _backfill_null_owner_id(conn: Connection, table: str) -> None:
    """回填表中 owner_id 为 NULL 的遗留行，避免 SET NOT NULL 失败。

    遗留数据的 owner_id 回填为模型默认值 "default"，保证既有无主资源
    在收紧为 NOT NULL 后仍可被访问（含 require_owner 的开发模式放行逻辑）。
    """
    conn.execute(
        sa.text(
            f"UPDATE {table} SET owner_id = 'default' WHERE owner_id IS NULL"
        )
    )


def _constraint_exists(conn: Connection, table: str, name: str) -> bool:
    """判断约束是否已存在（幂等保护，允许部分 DDL 生效后重跑迁移）。"""
    row = conn.execute(
        sa.text(
            "SELECT 1 FROM pg_constraint WHERE conname = :name "
            "AND conrelid = :table::regclass"
        ),
        {"name": name, "table": table},
    ).first()
    return row is not None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    # 清理孤儿行（引用了已删除实验的残留数据），否则外键约束创建会失败
    for table in ("experiment_variants", "experiment_metrics",
                  "experiment_results", "traffic_allocations"):
        op.execute(
            f"DELETE FROM {table} WHERE experiment_id NOT IN (SELECT id FROM experiments)"
        )
    # 先回填 NULL owner_id 遗留行，再收紧为 NOT NULL（幂等）
    _backfill_null_owner_id(bind, "documents")
    _backfill_null_owner_id(bind, "feedbacks")
    _backfill_null_owner_id(bind, "knowledge_bases")
    op.alter_column('documents', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('experiment_metrics', 'experiment_id',
               existing_type=sa.UUID(),
               nullable=False)
    if not _constraint_exists(bind, "experiment_metrics", "fk_experiment_metrics_experiment"):
        op.create_foreign_key('fk_experiment_metrics_experiment', 'experiment_metrics', 'experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('experiment_results', 'experiment_id',
               existing_type=sa.UUID(),
               nullable=False)
    if not _constraint_exists(bind, "experiment_results", "fk_experiment_results_experiment"):
        op.create_foreign_key('fk_experiment_results_experiment', 'experiment_results', 'experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('experiment_variants', 'experiment_id',
               existing_type=sa.UUID(),
               nullable=False)
    if not _constraint_exists(bind, "experiment_variants", "fk_experiment_variants_experiment"):
        op.create_foreign_key('fk_experiment_variants_experiment', 'experiment_variants', 'experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('feedbacks', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('knowledge_bases', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('traffic_allocations', 'experiment_id',
               existing_type=sa.UUID(),
               nullable=False)
    if not _constraint_exists(bind, "traffic_allocations", "fk_traffic_allocations_experiment"):
        op.create_foreign_key('fk_traffic_allocations_experiment', 'traffic_allocations', 'experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


# revision identifiers, used by Alembic.
revision: str = '8cb6e5b283ec'
down_revision: Union[str, Sequence[str], None] = 'b7d2c94a1f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_traffic_allocations_experiment', 'traffic_allocations', type_='foreignkey')
    op.alter_column('traffic_allocations', 'experiment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('knowledge_bases', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('feedbacks', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('fk_experiment_variants_experiment', 'experiment_variants', type_='foreignkey')
    op.alter_column('experiment_variants', 'experiment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('fk_experiment_results_experiment', 'experiment_results', type_='foreignkey')
    op.alter_column('experiment_results', 'experiment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('fk_experiment_metrics_experiment', 'experiment_metrics', type_='foreignkey')
    op.alter_column('experiment_metrics', 'experiment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('documents', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
