"""align schema with models: owner_id NOT NULL, experiment FKs

Revision ID: 8cb6e5b283ec
Revises: b7d2c94a1f30
Create Date: 2026-09-11 11:00:33.366857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb6e5b283ec'
down_revision: Union[str, Sequence[str], None] = 'b7d2c94a1f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 清理孤儿行（引用了已删除实验的残留数据），否则外键约束创建会失败
    for table in ("experiment_variants", "experiment_metrics",
                  "experiment_results", "traffic_allocations"):
        op.execute(
            f"DELETE FROM {table} WHERE experiment_id NOT IN (SELECT id FROM experiments)"
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('experiment_metrics', 'experiment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key('fk_experiment_metrics_experiment', 'experiment_metrics', 'experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('experiment_results', 'experiment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key('fk_experiment_results_experiment', 'experiment_results', 'experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('experiment_variants', 'experiment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key('fk_experiment_variants_experiment', 'experiment_variants', 'experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('feedbacks', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('knowledge_bases', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('traffic_allocations', 'experiment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key('fk_traffic_allocations_experiment', 'traffic_allocations', 'experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_traffic_allocations_experiment', 'traffic_allocations', type_='foreignkey')
    op.alter_column('traffic_allocations', 'experiment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('knowledge_bases', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('feedbacks', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('fk_experiment_variants_experiment', 'experiment_variants', type_='foreignkey')
    op.alter_column('experiment_variants', 'experiment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('fk_experiment_results_experiment', 'experiment_results', type_='foreignkey')
    op.alter_column('experiment_results', 'experiment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('fk_experiment_metrics_experiment', 'experiment_metrics', type_='foreignkey')
    op.alter_column('experiment_metrics', 'experiment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('documents', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
